# Generated by Django 5.0.3 on 2024-05-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_payment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingplace',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
